In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot("amazing restaurant",30)

[5, 29]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)


[[24, 19], [5, 29], [5, 2], [19, 12, 22], [24, 1, 22], [23, 19], [2, 1, 17], [12, 29], [12, 16], [3, 8]]


In [4]:
max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[24 19  0  0]
 [ 5 29  0  0]
 [ 5  2  0  0]
 [19 12 22  0]
 [24  1 22  0]
 [23 19  0  0]
 [ 2  1 17  0]
 [12 29  0  0]
 [12 16  0  0]
 [ 3  8  0  0]]


In [16]:
embeded_vector_size = 4

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [17]:
X = padded_reviews
y = sentiment

In [18]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [19]:
model.fit(X, y, epochs=50, verbose=0)

In [20]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - accuracy: 1.0000 - loss: 0.6388


1.0

In [22]:
weights = model.get_layer('embedding').get_weights()[0]
weights
# len(weights)

array([[-0.05770013, -0.00456189,  0.00212356,  0.01091667],
       [-0.04087631,  0.04273851,  0.04014853,  0.01127796],
       [-0.02062332,  0.04182855, -0.00875552, -0.07850205],
       [-0.06958045,  0.01935489, -0.03317203, -0.05231933],
       [ 0.01200472,  0.04784581,  0.00704189, -0.00293572],
       [ 0.04931554, -0.02434996, -0.00183591,  0.08179714],
       [-0.03687924, -0.03006491, -0.03775714, -0.00449021],
       [ 0.01021125, -0.001002  , -0.04248212, -0.0410434 ],
       [ 0.07866175, -0.03097372,  0.05857764,  0.06944074],
       [ 0.04535414, -0.02542895, -0.04004612,  0.03729136],
       [ 0.00892818,  0.04398669, -0.00344416,  0.02929291],
       [-0.04900514, -0.00555812, -0.0372018 , -0.01193704],
       [-0.05309177,  0.10373716, -0.02408319, -0.04340305],
       [-0.02547989,  0.03029367, -0.01452176,  0.0081264 ],
       [ 0.02679744, -0.0078164 ,  0.02771076,  0.01746016],
       [-0.00079381, -0.03579646, -0.00195342,  0.03418716],
       [ 0.05334884, -0.